#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.tests_sources = []

env_tests = env.Clone()

# We must disable the THREAD_LOCAL entirely in doctest to prevent crashes on debugging
# Since we link with /MT thread_local is always expired when the header is used
# So the debugger crashes the engine and it causes weird errors
# Explained in https://github.com/onqtam/doctest/issues/401
if env_tests["platform"] == "windows":
    env_tests.Append(CPPDEFINES=[("DOCTEST_THREAD_LOCAL", "")])

if env["disable_exceptions"]:
    env_tests.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env_tests.add_source_files(env.tests_sources, "*.cpp")
env_tests.add_source_files(env.test_sources, "test_validate_testing.cpp")
env_tests.add_source_files(env.test_sources, "core/*.cpp")
env_tests.add_source_files(env.test_sources, "core/config/*.cpp")
env_tests.add_source_files(env.test_sources, "core/input/*.cpp")
env_tests.add_source_files(env.test_sources, "core/io/*.cpp")
env_tests.add_source_files(env.test_sources, "core/math/*.cpp")
env_tests.add_source_files(env.test_sources, "core/object/*.cpp")
env_tests.add_source_files(env.test_sources, "core/os/*.cpp")
env_tests.add_source_files(env.test_sources, "core/string/*.cpp")
env_tests.add_source_files(env.test_sources, "core/templates/*.cpp")
env_tests.add_source_files(env.test_sources, "core/threads/*.cpp")
env_tests.add_source_files(env.test_sources, "core/variant/*.cpp")
env_tests.add_source_files(env.test_sources, "scene/*.cpp")
env_tests.add_source_files(env.test_sources, "servers/*.cpp")
env_tests.add_source_files(env.test_sources, "servers/rendering/*.cpp")

lib = env_tests.add_library("tests", env.tests_sources)
env.Prepend(LIBS=[lib])
