#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gltf = env_modules.Clone()

# Godot source files

env_gltf.add_source_files(env.modules_sources, "*.cpp")
env_gltf.add_source_files(env.modules_sources, "structures/*.cpp")

SConscript("extensions/SCsub")

if env.editor_build:
    env_gltf.add_source_files(env.modules_sources, "editor/*.cpp")

if env["tests"]:
    env_gltf.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gltf.add_source_files(env.test_sources, "./tests/*.cpp")
